//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-520 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.11.01 at 02:13:05 AM EDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.hibernate.org/xsd/hibernate-mapping", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.hibernate.internal.jaxb.mapping.hbm;
